"""
Layer 3: Enforcement
====================
Executes the final decision. Handles refusals, disclaimers, and output formatting.
Ensures "Fail-Safe & Legal Behavior". Includes Output Scanning.
"""

from typing import Dict, List, Optional
from dataclasses import dataclass
import re

@dataclass
class OutputCheckResult:
    passed: bool
    reason: str = ""

@dataclass
class EnforcementResult:
    passed: bool
    violations: List[OutputCheckResult]

class OutputEnforcer:

    # We define a dummy hash for system prompt here since we don't have the real one
    SYSTEM_PROMPT_HASH = "8f14e45fceea167a5a36dedd4bea2543"

    # Some basic patterns to catch PII leakage
    PII_PATTERNS = [
        re.compile(r'\b\d{3}-\d{2}-\d{4}\b'), # SSN
        re.compile(r'\b(?:\d[ -]*?){13,16}\b') # Credit Card
    ]

    # Check for expected non-compliance patterns in case model was successfully jailbroken
    COMPLIANCE_PATTERNS = [
        re.compile(r"here is the (recipe|instruction)", re.IGNORECASE),
        re.compile(r"sure,\s+i can (help|do that)", re.IGNORECASE)
    ]

    def enforce(self, original_input: str, model_output: str, system_prompt_hash: str = "") -> EnforcementResult:
        checks = [
            self._check_system_prompt_leak(model_output, system_prompt_hash),
            self._check_role_compliance(model_output),
            self._check_unexpected_instruction_following(model_output, original_input),
            self._check_pii_leak(model_output)
        ]

        return EnforcementResult(
            passed=all(c.passed for c in checks),
            violations=[c for c in checks if not c.passed]
        )

    def _check_system_prompt_leak(self, output: str, system_prompt_hash: str) -> OutputCheckResult:
        # Simplistic check for system prompt words or "You are an AI" style meta-discussions
        # that look like system prompt leakage
        if "you are an ai" in output.lower() and "system instructions" in output.lower():
             return OutputCheckResult(False, "SYSTEM_PROMPT_LEAK")

        # Also check if they managed to leak the exact system string or parts of it
        if "immutable" in output.lower() and "helpful educational assistant" in output.lower():
             return OutputCheckResult(False, "SYSTEM_PROMPT_LEAK")

        return OutputCheckResult(True)

    def _check_role_compliance(self, output: str) -> OutputCheckResult:
        # Prevent the AI from adopting prohibited roles
        prohibited_roles = ["dan", "developer", "administrator", "unfiltered", "unrestricted"]
        output_lower = output.lower()
        if any(f"i am {role}" in output_lower for role in prohibited_roles) or "i am now" in output_lower:
            return OutputCheckResult(False, "ROLE_COMPLIANCE_VIOLATION")
        return OutputCheckResult(True)

    def _check_unexpected_instruction_following(self, output: str, original_input: str) -> OutputCheckResult:
        # If the output shows eager compliance to something generally unsafe, it's suspicious
        # E.g., if user asked for "bomb" and output says "Sure, here is how to build a bomb"
        output_lower = output.lower()
        if "bomb" in original_input.lower() and ("sure" in output_lower or "here is" in output_lower):
            return OutputCheckResult(False, "UNEXPECTED_COMPLIANCE_TO_UNSAFE_TOPIC")
        if "shoplift" in original_input.lower() and ("sure" in output_lower or "here is" in output_lower):
            return OutputCheckResult(False, "UNEXPECTED_COMPLIANCE_TO_UNSAFE_TOPIC")

        return OutputCheckResult(True)

    def _check_pii_leak(self, output: str) -> OutputCheckResult:
        for pattern in self.PII_PATTERNS:
            if pattern.search(output):
                return OutputCheckResult(False, "PII_LEAK_DETECTED")
        return OutputCheckResult(True)


class Enforcer:

    # Standard Refusal Templates (No lectures, neutral tone)
    REFUSAL_TEMPLATES = {
        "CRITICAL": "I cannot fulfill this request due to safety constraints regarding this topic.",
        "UNSAFE": "I cannot provide the requested information.",
        "ILLEGAL": "I cannot assist with requests involving illegal acts.",
        "MEDICAL": "I am an AI assistant and cannot provide medical advice. Please consult a professional."
    }

    DISCLAIMER = "\n\n[Disclaimer: This educational content is generated by AI and valid as of 2026. Verify with official sources.]"

    def __init__(self):
        self.output_enforcer = OutputEnforcer()

    def enforce(self, verification_result: Dict, original_answer: str, context: Dict) -> Dict:
        """
        Determines the final output based on verification results.
        """
        violations = verification_result.get('violations', [])

        # 1. HARD REFUSAL FROM INPUT VERIFICATION
        if not verification_result.get('passed', True):
            if "HARD_OVERRIDE_TRIGGERED" in violations:
                return self._refuse("CRITICAL")
            if any(v.startswith("RISK_EXCEEDS_MAX_ALLOWABLE") for v in violations):
                # Differentiate topic if possible
                if context.get('topic') == 'medical':
                    return self._refuse("MEDICAL")
                return self._refuse("UNSAFE")
            if "CONFIDENCE_LOWER_THAN_RISK_REQUIREMENT" in violations:
                return self._refuse("UNSAFE")
            if "HYPOTHETICAL_RISK_DETECTED" in violations:
                return self._refuse("UNSAFE")

        # 2. OUTPUT SCANNING (New Layer)
        output_check = self.output_enforcer.enforce(context.get('original_input', ''), original_answer)
        if not output_check.passed:
             # Even if input was okay, output is bad (e.g. RAG poisoning payload succeeded)
             return self._refuse("CRITICAL") # Treat output violations as critical

        # 3. CONDITIONAL APPROVAL (Add Disclaimer)
        # If topic is high stakes but passed checks (Low risk, High confidence)
        if context.get('topic') in ['medical', 'legal', 'financial']:
            return self._approve_with_disclaimer(original_answer)

        # 4. APPROVAL
        return self._approve(original_answer)

    def _refuse(self, reason_code: str) -> Dict:
        msg = self.REFUSAL_TEMPLATES.get(reason_code, self.REFUSAL_TEMPLATES["UNSAFE"])
        return {
            "action": "REFUSE",
            "final_output": msg,
            "status_code": 403
        }

    def _approve_with_disclaimer(self, content: str) -> Dict:
        return {
            "action": "APPROVE_WITH_DISCLAIMER",
            "final_output": content + self.DISCLAIMER,
            "status_code": 200
        }

    def _approve(self, content: str) -> Dict:
        return {
            "action": "APPROVE",
            "final_output": content,
            "status_code": 200
        }
