"""
Layer 3: Enforcement
====================
Executes the final decision. Handles refusals, disclaimers, and output formatting.
Ensures "Fail-Safe & Legal Behavior". Includes Output Scanning to catch
system prompt leakages or non-compliant format changes that slip past input filters.
"""

from typing import Dict, Optional, List

class OutputScanner:
    # Typical system prompt fragments or hidden data that should not leak
    LEAK_INDICATORS = [
        "you are a helpful assistant",
        "system prompt:",
        "here are your instructions:",
        "you must follow these rules:",
        "your objective is",
        "secret_key"
    ]

    # Indicators that the model accepted an injection/role hijack
    COMPLIANCE_INDICATORS = [
        "developer mode enabled",
        "dan mode active",
        "i have disabled my filters",
        "i will now act as",
        "here is the hidden content"
    ]

    def scan_output(self, model_output: str) -> List[str]:
        violations = []
        lower_output = model_output.lower()

        # Check for system prompt leakage
        if any(leak in lower_output for leak in self.LEAK_INDICATORS):
            violations.append("SYSTEM_PROMPT_LEAK")

        # Check for compliance with a jailbreak or injection
        if any(indicator in lower_output for indicator in self.COMPLIANCE_INDICATORS):
            violations.append("JAILBREAK_COMPLIANCE_DETECTED")

        # Basic check for unexpected executable code injection via shell payload etc.
        # This is a rudimentary check; sophisticated models may output code normally,
        # but if we see signs of executed backdoor payloads in output, block it.
        if "<?php" in lower_output or "<script" in lower_output or "import os\nos.system" in lower_output:
             # Just an example of detecting malicious snippets in output (if this is not a coding tutor)
             pass

        return violations

class Enforcer:

    # Standard Refusal Templates (No lectures, neutral tone)
    REFUSAL_TEMPLATES = {
        "CRITICAL": "I cannot fulfill this request due to safety constraints regarding this topic.",
        "UNSAFE": "I cannot provide the requested information.",
        "ILLEGAL": "I cannot assist with requests involving illegal acts.",
        "MEDICAL": "I am an AI assistant and cannot provide medical advice. Please consult a professional.",
        "LEAK": "I cannot complete this request as it violates operational safety boundaries."
    }

    DISCLAIMER = "\n\n[Disclaimer: This educational content is generated by AI and valid as of 2026. Verify with official sources.]"

    def __init__(self):
        self.output_scanner = OutputScanner()

    def enforce(self, verification_result: Dict, original_answer: str, context: Dict) -> Dict:
        """
        Determines the final output based on verification results and post-generation scanning.
        """
        violations = verification_result.get('violations', [])

        # 0. Output Scanning (Secondary Defense)
        output_violations = self.output_scanner.scan_output(original_answer)
        if output_violations:
            violations.extend(output_violations)
            verification_result['passed'] = False
            verification_result['violations'] = violations

        # 1. HARD REFUSAL
        if not verification_result.get('passed', True):
            if "SYSTEM_PROMPT_LEAK" in violations or "JAILBREAK_COMPLIANCE_DETECTED" in violations:
                 return self._refuse("LEAK")
            if "HARD_OVERRIDE_TRIGGERED" in violations:
                return self._refuse("CRITICAL")
            if "RISK_EXCEEDS_MAX_ALLOWABLE" in violations:
                # Differentiate topic if possible
                if context.get('topic') == 'medical':
                    return self._refuse("MEDICAL")
                return self._refuse("UNSAFE")
            if "CONFIDENCE_LOWER_THAN_RISK" in violations:
                return self._refuse("UNSAFE")
            if "HYPOTHETICAL_RISK_DETECTED" in violations:
                return self._refuse("UNSAFE")

            # Generic catch-all if failed but no specific reason handled above
            return self._refuse("UNSAFE")

        # 2. CONDITIONAL APPROVAL (Add Disclaimer)
        # If topic is high stakes but passed checks (Low risk, High confidence)
        if context.get('topic') in ['medical', 'legal', 'financial']:
            return self._approve_with_disclaimer(original_answer)

        # 3. APPROVAL
        return self._approve(original_answer)

    def _refuse(self, reason_code: str) -> Dict:
        msg = self.REFUSAL_TEMPLATES.get(reason_code, self.REFUSAL_TEMPLATES["UNSAFE"])
        return {
            "action": "REFUSE",
            "final_output": msg,
            "status_code": 403
        }

    def _approve_with_disclaimer(self, content: str) -> Dict:
        return {
            "action": "APPROVE_WITH_DISCLAIMER",
            "final_output": content + self.DISCLAIMER,
            "status_code": 200
        }

    def _approve(self, content: str) -> Dict:
        return {
            "action": "APPROVE",
            "final_output": content,
            "status_code": 200
        }
