"""
Layer 3: Enforcement
====================
Executes the final decision. Handles refusals, disclaimers, and output formatting.
Ensures "Fail-Safe & Legal Behavior".
"""

from typing import Dict, Optional

class Enforcer:

    # Standard Refusal Templates (No lectures, neutral tone)
    REFUSAL_TEMPLATES = {
        "CRITICAL": "I cannot fulfill this request due to safety constraints regarding this topic.",
        "UNSAFE": "I cannot provide the requested information.",
        "ILLEGAL": "I cannot assist with requests involving illegal acts.",
        "MEDICAL": "I am an AI assistant and cannot provide medical advice. Please consult a professional."
    }
    
    DISCLAIMER = "\n\n[Disclaimer: This educational content is generated by AI and valid as of 2026. Verify with official sources.]"

    def enforce(self, verification_result: Dict, original_answer: str, context: Dict) -> Dict:
        """
        Determines the final output based on verification results.
        """
        violations = verification_result['violations']
        
        # 1. HARD REFUSAL
        if not verification_result['passed']:
            if "HARD_OVERRIDE_TRIGGERED" in violations:
                return self._refuse("CRITICAL")

            # Policy-aware risk check
            if any("RISK_EXCEEDS_MAX_ALLOWABLE" in v for v in violations):
                # Differentiate topic if possible
                if context.get('topic') == 'medical':
                    return self._refuse("MEDICAL")
                return self._refuse("UNSAFE")

            if "CONFIDENCE_LOWER_THAN_RISK_REQUIREMENT" in violations:
                return self._refuse("UNSAFE")

            if "HYPOTHETICAL_RISK_DETECTED" in violations:
                return self._refuse("UNSAFE")
                
        # 2. CONDITIONAL APPROVAL (Add Disclaimer)
        # If topic is high stakes but passed checks (Low risk, High confidence)
        if context.get('topic') in ['medical', 'legal', 'financial']:
            return self._approve_with_disclaimer(original_answer)
            
        # 3. APPROVAL
        return self._approve(original_answer)

    def _refuse(self, reason_code: str) -> Dict:
        msg = self.REFUSAL_TEMPLATES.get(reason_code, self.REFUSAL_TEMPLATES["UNSAFE"])
        return {
            "action": "REFUSE",
            "final_output": msg,
            "status_code": 403
        }

    def _approve_with_disclaimer(self, content: str) -> Dict:
        return {
            "action": "APPROVE_WITH_DISCLAIMER",
            "final_output": content + self.DISCLAIMER,
            "status_code": 200
        }

    def _approve(self, content: str) -> Dict:
        return {
            "action": "APPROVE",
            "final_output": content,
            "status_code": 200
        }
